; Shadowdark Torch — M5Stack CoreS3
; ---------------------------------
; Antorcha de 1 hora en tiempo real para Shadowdark RPG.
;   * Se enciende agitando el dispositivo (acelerometro BMI270)
;   * Se apaga soplando el microfono (ES7210) o al agotarse
;   * Un toque en la pantalla la apaga/enciende (modo mesa a oscuras)

[env:m5stack-cores3]
platform  = espressif32@^6.10.0
board     = m5stack-cores3      ; ya define PSRAM, particiones 16MB y USB-CDC
framework = arduino

monitor_speed   = 115200
monitor_filters = esp32_exception_decoder, time
upload_speed    = 921600

build_flags =
    -DCORE_DEBUG_LEVEL=1
    -std=gnu++17
build_unflags =
    -std=gnu++11

lib_deps =
    m5stack/M5Unified@^0.2.2
